---
title: "Simple Logistic Regression (Part 1)"
subtitle: "Class Activity"
author: "Andrew Seaman"
date: "2026-03-09"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

<!-- ------ -->
<!-- SETUP: -->
<!-- ------ -->

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(mosaic)
library(pander)
library(tidyverse)
```

<!-- Setup End -->





<!-- ---------- -->
<!-- QUESTIONS: -->
<!-- ---------- -->

## 1.
> _[Question]_

[Response]

```{r}
# a.
kf2 <- KidsFeet %>% 
  mutate(sex_dummy = ifelse(sex == "B",1,0))

# b.
myglm <- glm(sex_dummy ~ length, data=kf2, family=binomial)

# c.
predict(myglm, newdata = data.frame(length=25), type="response")

# d.
ggplot(kf2, aes(x=length,y=sex_dummy))+
  geom_point()+
  # > This code below did this equation:
  # plot(Y ~ X, data=YourDataSet)
  # curve(exp(𝑏0+𝑏1*x)/(1 + exp( 𝑏0+𝑏1*x)), add = TRUE)
  # > "Just know, there is an equation actually graphing the line." - Bro. Saunders
  geom_smooth(method="glm", method.args = list(family="binomial"), se = FALSE)+
  theme_bw()+
  labs(
    title = "Practice `predict()` function using a GLM model",
    subtitle = "Logistic Regression - W10",
    x = "Foot Length",
    y = "Sex (G=0, B=1)"
  )
```

<!-- Q1. End -->




<!-- Questions End -->




<!-- -------- -->
<!-- FILE END -->
<!-- -------- -->