---
title: "W10 - Logistic Regression"
subtitle: "Skills Quiz"
author: "Andrew Seaman"
date: "03/16/2026"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    toc-depth: 6
    code_folding: hide
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries. Modify list as needed.
library(tidyverse)
library(mosaic)
library(mosaicData)
library(ResourceSelection)
library(pander)
```


<!-- START: ALL -->
# Questions



<!-- START: Main Tabset -->
# {.tabset .tabset-pills .tabset-fade}



<!-- START: Summary -->
## Summary

----

### Introduction
[Introduction text]

<BR />

### Questions (4)

##### Q3

* Plotting the logistic regression curve
* Testing the line-of-best-fit.

##### Q4
* Plotting the logistic regression curve
* Testing the line-of-best-fit.

<!-- END: Summary -->





<!-- START: Q3 -->
## Q3

----

##### 3.1

What values should be used in place of b0 and b1 in the following command to place the logistic curve on the plot you now have in R?

```{r}
# 3.1

# a) 
infert.glm <- glm( (spontaneous > 0) ~ age, data=infert, family=binomial)

# b)
summary(infert.glm)

# c)
b <- coef(infert.glm)

# d)
plot( (spontaneous > 0) ~ age, data=infert)
curve( exp(b[1] + b[2]*x)/(1 + exp(b[1] + b[2]*x)), add=TRUE)
```


##### 3.2
```{r}
# 3.2

# a) the data
table(infert$age)

# ***WARNING: THIS WAS THE WRONG TEST TO USE. USED RARELY.***
# b) Hosmer-Lemeshow Goodness-of-Fit Test
hoslem.test(infert.glm$y, infert.glm$fitted, g = 10)

# ***NOTE: THIS WAS THE RIGHT TEST TO USE. USED OFTEN.***
# c) The pchisq command allows you to compute p-values from the chi-squared distribution.
residual_deviance <- deviance(infert.glm)
df_residuals <- df.residual(infert.glm)

pchisq(residual_deviance, df_residuals, lower.tail=FALSE) # Output: 0.0001570983 (digits=5 | 0.00016)
```





<!-- START: Q4 -->
## Q4

----

##### 4.1
```{r}
# 4.1

# a) 
gal.glm <- glm( (sex == "M") ~ height, data=Galton, family=binomial)

# b)
summary(gal.glm)

# c)
b <- coef(gal.glm)

# d)
plot( (sex == "M") ~ height, data=Galton)
curve( exp(b[1] + b[2]*x)/(1 + exp(b[1] + b[2]*x)), add=TRUE)
```

##### 4.2
```{r}
# 4.2

# a) Calculate the e^beta_1
estimated_eb1 <- exp(gal.glm$coefficients["height"])
estimated_eb1

# b) Predict the probability that a person who is (x=) 65 inches tall is male. 
pred <- predict(gal.glm, newdata = data.frame(height=65), type="response")
pred

# c) Conduct Hosmer and Lemeshow's Goodness of Fit test with g=10
hoslem.test(gal.glm$y, gal.glm$fitted, g = 10)
```

<!-- END: Q4 -->





#

<!-- END: Main Tabset -->

<!-- END: ALL -->