---
title: "Simple Linear Regression"
subtitle: "Skills Quiz"
author: "STUDENT NAME"
date: "YYYY-MMM-DD"
output: 
  html_document:
    theme: journal
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries. Modify list as needed.
library(tidyverse)
library(mosaic)
library(mosaicData)
library(DT)
library(pander)
```


<!-- START: ALL -->
# Questions





<!-- START: Main Tabset -->
# {.tabset .tabset-pills .tabset-fade}





<!-- START: Summary -->
## Summary

----

### Introduction
[Introduction text]

<BR />

### Questions [# of questions]

##### Q1
\[summary]

##### Q2
\[summary]

##### Q3
\[summary]

##### Q4
\[summary]

##### Q5
\[summary]

##### Q6
\[summary]

##### Q7
\[summary]

##### Q8
\[summary]

##### Q9
\[summary]

##### Q10
\[summary]

<!-- END: Summary -->


<!-- START: Q2 -->
## Q2

----

##### 2.1
```{r}
# 2.1
plot(Height ~ Volume, data=trees)
trees.lm <- lm(Height ~ Volume, data=trees)
abline(trees.lm)
```

##### 2.2
```{r}
# 2.2
par(mfrow=c(1,2))
plot(trees.lm, which=1:2)
par(mfrow = c(1,1)) #This resets your plotting window for future plots.
```





<!-- START: Q3 -->
## Q3

----

##### 3.1
```{r}
# 3.1
plot(eruptions ~ waiting, data=faithful)
faith.lm <- lm(waiting ~ eruptions, data=faithful)
abline(faith.lm)
```

##### 3.2
```{r}
# 3.2
par(mfrow=c(1,2))
plot(faith.lm, which=1:2)
par(mfrow = c(1,1)) #This resets your plotting window for future plots.
```

##### 3.3
```{r}
# 3.3
pander(summary(faith.lm))
```

##### 3.4
```{r}
# 3.4
par(mfrow=c(1,3))
plot(faith.lm,which=1:2)
plot(faith.lm$residuals)
```

##### 3.5
```{r}
# 3.5
faith.lm$coefficients
```

<!--
---------------------------------------------------------------
     &nbsp;        Estimate   Std. Error   t value   Pr(>|t|)  
----------------- ---------- ------------ --------- -----------
 **(Intercept)**    33.47       1.155       28.99    7.136e-85 

  **eruptions**     10.73       0.3148      34.09    8.13e-100 
---------------------------------------------------------------


--------------------------------------------------------------
 Observations   Residual Std. Error   $R^2$    Adjusted $R^2$ 
-------------- --------------------- -------- ----------------
     272               5.914          0.8115       0.8108     
--------------------------------------------------------------

Table: Fitting linear model: waiting ~ eruptions
-->

##### 3.6
```{r}
# 3.6
predict(faith.lm, data.frame(X=0))
```

#

<!-- END: Main Tabset -->

<!-- END: ALL -->