---
title: "ANOVA"
subtitle: "Skills Quiz"
author: "Andrew Seaman"
date: "2025-Aug-4"
output: 
  html_document:
    theme: journal
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries. Modify list as needed.
library(tidyverse)
library(mosaic)
library(mosaicData)
library(DT)
library(pander)
```



<!-- START: ALL -->
# Questions





<!-- START: Main Tabset -->
# {.tabset .tabset-pills .tabset-fade}

<!-- START: Q1 -->
## Q1

----

Learn about factors and levels.

```{r}
wb <- warpbreaks
```

```{r}
tg <- ToothGrowth
```

<!-- END: Q1 -->





<!-- START: Q2 -->
## Q2

----

The mathematical model for the One-Way ANOVA hypothesis test.

<!-- END: Q2 -->





<!-- START: Q3 -->
## Q3

----

Running an ANOVA test and drawing conclusions. Checking the requirements of the ANOVA test to validate the reliability of the test results. Plotting the means to gain further insight into what the ANOVA test told us was likely to be the case.

##### 3.1
```{r}
# 3.1

library(car) 
```

##### 3.2
```{r}
# 3.2

friendly.aov <- aov(correct ~ condition, data=Friendly)
summary(friendly.aov)
```

##### 3.3
```{r}
# 3.3

par(mfrow=c(1,2))
plot(friendly.aov, which=1:2)
```

##### 3.4
```{r}
# 3.4

# Consider the following plot in R that shows the means of each group with a line as well as the points from each group (jittered or wiggled a little in the horizontal direction so that they don't overlap).

xyplot(correct ~ condition, data=Friendly, jitter.x=TRUE, type=c("p","a"))
```

<!-- END: Q3 -->





<!-- START: Q4 -->
## Q4

----

The three sets of hypotheses are provided in the quiz.

##### 4.1
```{r}
# 4.1

tooth.aov <- aov(len ~ supp + as.factor(dose) + supp:as.factor(dose), data = ToothGrowth)

summary(tooth.aov)
```

##### 4.2
```{r}
# 4.2

par(mfrow=c(1,2))
plot(tooth.aov, which=1:2)
```

##### 4.3
```{r}
# 4.3

xyplot(len ~ supp, data=ToothGrowth, type=c("p","a"), main="Orange Juice Showing Longer Teeth on Average in Guinea Pigs", ylab="Length of Odontoblasts", xlab="Vitamin C Delivery Method")
```

##### 4.4
```{r}
# 4.4

# Numerical Summary: 

numSummary1 <- ToothGrowth %>% 
  group_by(supp) %>% 
  summarise(
    `Mean Lenth of Odontoblasts` = round(mean(len, na.rm = TRUE), 1),
    .groups = "drop"
  )

pander(numSummary1)
```

##### 4.5
```{r}
# 4.5

xyplot( len ~ dose, data=ToothGrowth, type=c("p","a"), main="Higher Doses Showing Longer Teeth on Average in Guinea Pigs", ylab="Length of Odontoblasts", xlab="Dosage Level in mg/day")
```

##### 4.6
```{r}
# 4.6

# Numerical Summary: 

numSummary2 <- ToothGrowth %>% 
  group_by(as.factor(dose)) %>% 
  summarise(
    `Mean Lenth of Odontoblasts` = round(mean(len, na.rm = TRUE), 1),
    .groups = "drop"
  )

pander(numSummary2)
```

##### 4.7
```{r}
# 4.7

xyplot( len ~ dose, data=ToothGrowth, groups=supp, type=c("p","a"), auto.key=TRUE, main="Delivery Methods are Equal at High Doses of VC", ylab="Length of Odontoblasts in Guinea Pigs", xlab="Dosage Level of Vitamin C in mg/day")
```

##### 4.8
```{r}
# 4.8

# Numerical Summary: 

numSummary3 <- ToothGrowth %>% 
  group_by(supp, as.factor(dose)) %>% 
  summarise(
    `Mean Lenth of Odontoblasts` = round(mean(len, na.rm = TRUE), 1),
    .groups = "drop"
  )

pander(numSummary3)
```

<!-- END: Q4 -->






#

<!-- END: Main Tabset -->

<!-- END: ALL -->