---
title: "Randomization Testing"
subtitle: "Skills Quiz"
author: "STUDENT NAME"
date: "YYYY-MMM-DD"
output: 
  html_document:
    theme: journal
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries. Modify list as needed.
library(tidyverse)
library(mosaic)
library(mosaicData)
library(DT)
library(pander)
```


<!-- START: ALL -->
# Questions





<!-- START: Main Tabset -->
# {.tabset .tabset-pills .tabset-fade}





<!-- START: Summary -->
## Summary

----

### Introduction
[Introduction text]

<BR />

### Questions [# of questions]

##### Q1
\[summary]

##### Q2
\[summary]

##### Q3
\[summary]

##### Q4
\[summary]

##### Q5
\[summary]

##### Q6
\[summary]

##### Q7
\[summary]

##### Q8
\[summary]

##### Q9
\[summary]

##### Q10
\[summary]

<!-- END: Summary -->





<!-- START: Q1 -->
## Q1

----

##### Introduction
[Introduction text]

##### 1.1
```{r}
# 1.1

```

##### 1.2
```{r}
# 1.2

```

##### 1.3
```{r}
# 1.3

```

##### 1.4
```{r}
# 1.4

```

##### 1.5
```{r}
# 1.5

```

##### 1.6
```{r}
# 1.6

```

##### 1.7
```{r}
# 1.7

```

##### 1.8
```{r}
# 1.8

```

##### 1.9
```{r}
# 1.9

```

##### 1.10
```{r}
# 1.10

```

<!-- END: Q1 -->





<!-- START: Q2 -->
## Q2

----

##### 2.1
```{r}
# 2.1

```

##### 2.2
```{r}
# 2.2

```

##### 2.3
```{r}
# 2.3

```

##### 2.4
```{r}
# 2.4

```

##### 2.5
```{r}
# 2.5

```

##### 2.6
```{r}
# 2.6

```

##### 2.7
```{r}
# 2.7

```

##### 2.8
```{r}
# 2.8

```

##### 2.9
```{r}
# 2.9

```

##### 2.10
```{r}
# 2.10

```

<!-- END: Q2 -->





<!-- START: Q3 -->
## Q3

----

##### 3.1
```{r}
# 3.1

```

##### 3.2
```{r}
# 3.2

```

##### 3.3
```{r}
# 3.3

```

##### 3.4
```{r}
# 3.4

```

##### 3.5
```{r}
# 3.5

```

##### 3.6
```{r}
# 3.6

```

##### 3.7
```{r}
# 3.7

```

##### 3.8
```{r}
# 3.8

```

##### 3.9
```{r}
# 3.9

```

##### 3.10
```{r}
# 3.10

```

<!-- END: Q3 -->





<!-- START: Q4 -->
## Q4

----

##### 4.1
```{r}
# 4.1

```

##### 4.2
```{r}
# 4.2

```

##### 4.3
```{r}
# 4.3

```

##### 4.4
```{r}
# 4.4

```

##### 4.5
```{r}
# 4.5

```

##### 4.6
```{r}
# 4.6

```

##### 4.7
```{r}
# 4.7

```

##### 4.8
```{r}
# 4.8

```

##### 4.9
```{r}
# 4.9

```

##### 4.10
```{r}
# 4.10

```

<!-- END: Q4 -->





<!-- START: Q5 -->
## Q5

----

##### 5.1
```{r}
# 5.1

```

##### 5.2
```{r}
# 5.2

```

##### 5.3
```{r}
# 5.3

```

##### 5.4
```{r}
# 5.4

```

##### 5.5
```{r}
# 5.5

```

##### 5.6
```{r}
# 5.6

```

##### 5.7
```{r}
# 5.7

```

##### 5.8
```{r}
# 5.8

```

##### 5.9
```{r}
# 5.9

```

##### 5.10
```{r}
# 5.10

```

<!-- END: Q5 -->





<!-- START: Q6 -->
## Q6

----

##### 6.1
```{r}
# 6.1

```

##### 6.2
```{r}
# 6.2

```

##### 6.3
```{r}
# 6.3

```

##### 6.4
```{r}
# 6.4

```

##### 6.5
```{r}
# 6.5

```

##### 6.6
```{r}
# 6.6

```

##### 6.7
```{r}
# 6.7

```

##### 6.8
```{r}
# 6.8

```

##### 6.9
```{r}
# 6.9

```

##### 6.10
```{r}
# 6.10

```

<!-- END: Q6 -->





<!-- START: Q7 -->
## Q7

----

##### 7.1
```{r}
# 7.1

```

##### 7.2
```{r}
# 7.2

```

##### 7.3
```{r}
# 7.3

```

##### 7.4
```{r}
# 7.4

```

##### 7.5
```{r}
# 7.5

```

##### 7.6
```{r}
# 7.6

```

##### 7.7
```{r}
# 7.7

```

##### 7.8
```{r}
# 7.8

```

##### 7.9
```{r}
# 7.9

```

##### 7.10
```{r}
# 7.10

```

<!-- END: Q7 -->





<!-- START: Q8 -->
## Q8

----

##### 8.1
```{r}
# 8.1

```

##### 8.2
```{r}
# 8.2

```

##### 8.3
```{r}
# 8.3

```

##### 8.4
```{r}
# 8.4

```

##### 8.5
```{r}
# 8.5

```

##### 8.6
```{r}
# 8.6

```

##### 8.7
```{r}
# 8.7

```

##### 8.8
```{r}
# 8.8

```

##### 8.9
```{r}
# 8.9

```

##### 8.10
```{r}
# 8.10

```  

<!-- END: Q8 -->





<!-- START: Q9 -->
## Q9

----

##### 9.1
```{r}
# 9.1

```

##### 9.2
```{r}
# 9.2

```

##### 9.3
```{r}
# 9.3

```

##### 9.4
```{r}
# 9.4

```

##### 9.5
```{r}
# 9.5

```

##### 9.6
```{r}
# 9.6

```

##### 9.7
```{r}
# 9.7

```

##### 9.8
```{r}
# 9.8

```

##### 9.9
```{r}
# 9.9

```

##### 9.10
```{r}
# 9.10

``` 

<!-- END: Q9 -->





<!-- START: Q10 -->
## Q10

----

##### 10.1
```{r}
# 10.1

```

##### 10.2
```{r}
# 10.2

```

##### 10.3
```{r}
# 10.3

```

##### 10.4
```{r}
# 10.4

```

##### 10.5
```{r}
# 10.5

```

##### 10.6
```{r}
# 10.6

```

##### 10.7
```{r}
# 10.7

```

##### 10.8
```{r}
# 10.8

```

##### 10.9
```{r}
# 10.9

```

##### 10.10
```{r}
# 10.10

```

<!-- END: Q10 -->





#

<!-- END: Main Tabset -->

<!-- END: ALL -->