---
title: "Multiple Linear Regression"
subtitle: "Assesment Quiz"
author: "Andrew Seaman"
date: "2025-MM-DD"
output: 
  html_document:
    theme: journal
    toc: true
    toc_float: true
    code_folding: hide
---

<!-- ------ -->
<!-- SETUP: -->
<!-- ------ -->

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(mosaic)
library(pander)
library(tidyverse)
```

<!-- Setup End -->










<!-- ---------- -->
<!-- QUESTIONS: -->
<!-- ---------- -->

## 1.
> _[Question]_

[Response]

```{r}
# a.
kf2 <- KidsFeet %>% 
  mutate(gender = ifelse(sex =="G", 1, 0))

# b.
mylm <- lm(length ~ width + gender + width:gender, data = kf2)

# c.
summary(mylm)
```

<!-- Q1. End -->










## 2.
> _[Question]_

[Response]

```{r}
#a. 
cars <- datasets::cars
# b.
cars2 <- cars %>% 
  mutate()

# c.
mylm <- lm(dist ~ speed + I(speed^2), data=cars2)

# d.
summary(mylm) %>% pander()

# e.


```

<!-- Q2. End -->










## 3.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q3. End -->










## 4.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q4. End -->










## 5.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q5. End -->










## 6.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q6. End -->










## 7.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q7. End -->










## 8.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q8. End -->










## 9.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q9. End -->










## 10.
> _[Question]_

[Response]
```{r}
# a.


# b.


# c.


# d.


```

<!-- Q10. End -->


<!-- Questions End -->




<!-- -------- -->
<!-- FILE END -->
<!-- -------- -->