---
title: "Chi Squared Test"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---


<!-- Directions

Come up with a chi squared test analysis of your own creation. 

* Write the Background and clearly state your question. Then collect data and perform the chi-squared test analysis in order to answer your question. Use the proper order of first, ask the question, then second, figure out the answer.

* You can use data from 
    - An R data set
    - the internet (like weather data, Facebook data, or sports data) 
    - your own experiment 
    - your own observational study
* However,     
    - Do not violate the "Human Subjects Rules" of the university: http://www.byui.edu/executive-strategy-and-planning/institutional-research/research-and-assessments/research-and-surveys

* You need a sample size large enough to meet the requirements of the chi squared test. Unfortunately, the sample size is completely dependent on the situation you select. A good rule of thumb is 10 observations per "combination-group" in your data.

-->


## Background

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(pander)
library(mosaic)
library(haven)
gss2021 <- read_sas("../../Data/gss2021.sas7bdat", 
    NULL)
```


```{r}
table(gss2021$HLTHMNTL)

table(gss2021$GOD)

table(gss2021$GOD, gss2021$HLTHMNTL)
```


```{r}
mytable <- table(gss2021$GOD, gss2021$HLTHMNTL)

rownames(mytable) <- c(
  "Don't believe", 
  "Don't know, no way to find out", 
  "Higher power", 
  "Believe sometimes", 
  "Believe with doubts", 
  "No doubts"
  )

colnames(mytable) <- c(
  "Excellent", 
  "Very good", 
  "Good", 
  "Fair", 
  "Poor"
  )

pander(mytable)
```

```{r}
barplot(t(mytable), beside=TRUE, legend.text=TRUE, xlim=c(0,50), 
        cex.names=0.2)
```


```{r message=FALSE, warning=FALSE}
chisq.test(mytable) %>%
  pander(caption="Chi-squared Test Results")
```



## Counts Tables {.tabset .tabset-pills}

```{r}
mytest <- chisq.test(mytable)
```

### Observed

```{r}
pander(mytest$observed, caption="Observed Counts")
```

### Expected

```{r}
pander(mytest$expected, caption="Expected Counts")
```

### Residuals

```{r}
pander(mytest$residuals, caption="Residuals", 
       split.table=Inf)

barplot(t(mytest$residuals), beside=TRUE, legend.text=TRUE, xlim=c(0,60), 
        cex.names=0.2)
```

